version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: full_stack_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass_dev
      MYSQL_DATABASE: full_stack_pms_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: full_stack_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data: